
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, AlignmentType, HeadingLevel, BorderStyle, WidthType, ShadingType, LevelFormat, PageBreak, VerticalAlign } = require('docx');
const fs = require('fs');

const bdr = { style: BorderStyle.SINGLE, size: 1, color: "888888" };
const borders = { top:bdr, bottom:bdr, left:bdr, right:bdr };

const h1 = (t) => new Paragraph({ heading:HeadingLevel.HEADING_1, spacing:{before:400,after:180}, children:[new TextRun({text:t,bold:true,size:30,font:"Times New Roman",color:"1F3864",allCaps:true})] });
const h2 = (t) => new Paragraph({ heading:HeadingLevel.HEADING_2, spacing:{before:320,after:140}, children:[new TextRun({text:t,bold:true,size:26,font:"Times New Roman",color:"2E75B6"})] });
const h3 = (t) => new Paragraph({ heading:HeadingLevel.HEADING_3, spacing:{before:240,after:100}, children:[new TextRun({text:t,bold:true,italics:true,size:24,font:"Times New Roman",color:"1F3864"})] });
const h4 = (t) => new Paragraph({ heading:HeadingLevel.HEADING_4, spacing:{before:160,after:80}, children:[new TextRun({text:t,bold:true,size:22,font:"Times New Roman"})] });
const p = (text, opts={}) => new Paragraph({ alignment:AlignmentType.JUSTIFIED, spacing:{before:100,after:100,line:360}, indent:{firstLine:opts.ni?0:720}, children:[new TextRun({text,size:24,font:"Times New Roman",...opts})] });
const pni = (text, opts={}) => p(text,{...opts,ni:true});
const bul = (text) => new Paragraph({ numbering:{reference:"bullets",level:0}, spacing:{before:80,after:80}, children:[new TextRun({text,size:23,font:"Times New Roman"})] });
const code = (text) => new Paragraph({ spacing:{before:80,after:80}, children:[new TextRun({text,size:20,font:"Courier New",color:"D32F2F",bold:false})] });
const cen = (text, opts={}) => new Paragraph({ alignment:AlignmentType.CENTER, spacing:{before:100,after:100}, children:[new TextRun({text,size:24,font:"Times New Roman",...opts})] });
const sp = () => new Paragraph({children:[new TextRun("")],spacing:{before:60,after:60}});
const pb = () => new Paragraph({children:[new PageBreak()]});

const doc = new Document({
  numbering:{ config:[
    {reference:"bullets",levels:[{level:0,format:LevelFormat.BULLET,text:"\u2022",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]},
    {reference:"numbers",levels:[{level:0,format:LevelFormat.DECIMAL,text:"%1.",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]}
  ]},
  styles:{ default:{document:{run:{font:"Times New Roman",size:24}}}, paragraphStyles:[
    {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:30,bold:true,font:"Times New Roman",color:"1F3864"},paragraph:{spacing:{before:400,after:180},outlineLevel:0}},
    {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:26,bold:true,font:"Times New Roman",color:"2E75B6"},paragraph:{spacing:{before:320,after:140},outlineLevel:1}},
  ]},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,right:1260,bottom:1440,left:1440}}},
  children:[

    // TITLE
    sp(),sp(),sp(),
    cen("AI Career Guidance Agent: Complete Technical Breakdown",{bold:true,size:32}),
    cen("A Comprehensive Guide to Backend Architecture, Classes, and Interview Preparation",{size:26,italics:true}),
    sp(),sp(),
    cen("Sakib Ayan Sheikh",{size:24,bold:true}),
    cen("Full Stack Developer",{size:22}),
    cen("ayansheikh8767@gmail.com",{size:22}),
    sp(),sp(),sp(),
    pb(),

    // TABLE OF CONTENTS
    h1("Table of Contents"),
    bul("Part 1: Project Overview & Architecture"),
    bul("Part 2: Backend Tech Stack & Dependencies"),
    bul("Part 3: Database Schema - Every Table Explained"),
    bul("Part 4: Authentication & Security Flow"),
    bul("Part 5: Core Service Classes - Line by Line"),
    bul("Part 6: Controller Classes - Request Handling"),
    bul("Part 7: Entity Classes & Relationships"),
    bul("Part 8: Key Algorithms - Recommendation & Skill Ordering"),
    bul("Part 9: Resume Analysis Pipeline"),
    bul("Part 10: Email Verification & Password Reset"),
    bul("Part 11: Admin Panel & Content Management"),
    bul("Part 12: Frontend Integration - How Frontend Calls Backend"),
    bul("Part 13: Common Interview Questions & Answers"),
    sp(),pb(),

    // PART 1
    h1("Part 1: Project Overview & Architecture"),
    h2("1.1 What is AI Career Guidance Agent?"),
    p("AI Career Guidance Agent is a full-stack web application that helps students figure out their tech career path, identify the skills they need to learn, get those skills in the right order, analyze their resume, and track their learning progress. Think of it as a unified platform that replaces at least 5 different tools students would otherwise use separately."),
    h2("1.2 The Problem It Solves"),
    p("Most students hit a wall: they want a tech career but don't know which one, which skills are needed, what order to learn them in, and whether their resume is ready. Existing tools either solve one piece (just course recommendations) or are generic (everyone gets the same advice). AI Career Guidance Agent personalizes everything and keeps it all in one place."),
    h2("1.3 Three-Tier Architecture"),
    h3("Frontend Layer"),
    p("React.js single-page application. Built with Vite for fast builds. Uses Tailwind CSS for styling. React Router for navigation. Axios for API calls. Stores JWT token in localStorage. AuthContext manages user login state globally."),
    h3("API Layer"),
    p("REST API using HTTPS/JSON. JWT-based stateless authentication. Over 30 endpoints covering all operations. Custom exception handling that returns standardized error responses."),
    h3("Backend Layer"),
    p("Java Spring Boot 4 framework. Spring Security 6 for authentication. Spring Data JPA for database access with Hibernate ORM. Maven for dependency management. Scheduled tasks for cleanup operations."),
    h3("Database Layer"),
    p("PostgreSQL relational database. 10 primary tables. Spring Data JPA repositories for each entity. Proper foreign key constraints and unique indexes."),
    h3("AI/External Services"),
    p("Google Gemini 2.5 Flash API for AI features. Gmail SMTP for sending emails. Both accessed via REST/HTTP from the backend."),
    sp(),pb(),

    // PART 2
    h1("Part 2: Backend Tech Stack & Dependencies"),
    h2("2.1 Maven Dependencies (Key Ones)"),
    h3("Spring Boot Starters"),
    code("spring-boot-starter-web — Enables REST API development with embedded Tomcat"),
    code("spring-boot-starter-security — Provides Spring Security 6 for authentication/authorization"),
    code("spring-boot-starter-data-jpa — Enables Spring Data JPA for database access"),
    code("spring-boot-starter-mail — Spring Mail for sending emails via SMTP"),
    h3("Database & ORM"),
    code("postgresql — PostgreSQL JDBC driver"),
    code("hibernate-core — ORM framework for database operations"),
    code("jakarta.persistence-api — JPA annotations (@Entity, @Column, etc.)"),
    h3("Security & JWT"),
    code("spring-security-crypto — BCrypt for password hashing"),
    code("jjwt (0.11.5) — JWT library for creating and validating tokens"),
    h3("Utilities"),
    code("lombok — Annotation processor for @Getter, @Setter, @AllArgsConstructor, etc."),
    code("pdfbox (2.0.29) — Apache PDFBox for extracting text from PDF files"),
    code("jackson-databind — JSON serialization/deserialization for REST responses"),
    h2("2.2 Maven Configuration"),
    code("Java version: 17 or higher (uses modern language features)"),
    code("Spring Boot version: 4.0+"),
    code("Build output: Executable JAR with all dependencies embedded"),
    sp(),pb(),

    // PART 3
    h1("Part 3: Database Schema - Every Table Explained"),
    h2("3.1 User Table"),
    h3("Purpose"),
    p("Stores user account information and authentication credentials."),
    h3("Columns"),
    bul("id (Long, Primary Key) — Unique identifier for each user"),
    bul("email (String, Unique) — Email address, must be unique"),
    bul("password (String) — BCrypt-hashed password, never stored in plain text"),
    bul("full_name (String) — User's full name"),
    bul("role (Enum: USER, ADMIN) — Determines what the user can access"),
    bul("is_verified (Boolean) — False until they click email verification link"),
    bul("created_at (LocalDateTime) — Timestamp when account was created"),
    h3("Relationships"),
    bul("One-to-One with UserProfile — Each user has exactly one profile with their onboarding answers"),
    bul("One-to-Many with Resume — A user can upload multiple resumes"),
    bul("One-to-Many with UserSkillProgress — A user tracks progress for multiple skills"),
    bul("One-to-Many with EmailVerificationToken — Tokens associated with this user"),
    h3("Key Interview Points"),
    p("The password is never stored as plain text — it's hashed with BCrypt. When a user logs in, we hash their input and compare it to the stored hash. The isVerified field is Boolean (not boolean) so we can distinguish between true, false, and null. Null is used for accounts created before verification was a feature."),

    h2("3.2 UserProfile Table"),
    h3("Purpose"),
    p("Stores the answers from the onboarding questionnaire. Used by the recommendation algorithm."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("user_id (Foreign Key to User)"),
    bul("interest_areas (String) — Comma-separated tags like 'backend,databases,scalability'"),
    bul("work_style_preferences (String) — Comma-separated like 'independent,analytical,remote'"),
    bul("career_goals (String) — Comma-separated like 'fast_growth,good_salary,impact'"),
    bul("education_level (String) — 'High School', 'Bachelor', 'Master', etc."),
    bul("known_skill_names (String) — Comma-separated skill names they already know"),
    bul("weekly_study_hours (Integer) — How many hours per week they can study"),
    bul("onboarding_completed_at (LocalDateTime) — When they finished the 6-step flow"),
    h3("Key Interview Points"),
    p("These fields are comma-separated strings, not arrays in the database. When we use them in the recommendation algorithm, we split them in Java code. This design keeps the schema simple. The recommendation algorithm reads these fields and scores every career against them using tag overlap matching."),

    h2("3.3 Career Table"),
    h3("Purpose"),
    p("Stores information about each career path (Java Backend Developer, Frontend Engineer, DevOps Engineer, etc.)."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("title (String) — 'Java Backend Developer', 'Frontend Engineer', etc."),
    bul("description (String) — Long text describing the career"),
    bul("demand_level (Enum: HIGH, MEDIUM, LOW) — How in-demand is this career"),
    bul("average_salary (Integer) — In USD or local currency"),
    bul("interest_tags (String) — Comma-separated tags like 'backend,databases,scalability'"),
    bul("work_style_tags (String) — 'independent,analytical,collaborative'"),
    bul("goal_tags (String) — 'growth,salary,impact,learning'"),
    bul("created_at (LocalDateTime)"),
    h3("Relationships"),
    bul("Many-to-Many with Skill through career_skills junction table"),
    bul("One-to-Many with Resource"),
    bul("One-to-Many with UserCareerInterest"),
    h3("Key Interview Points"),
    p("The tag fields are how we match careers to students. A student might be interested in 'backend' and 'databases'. A career might have interest_tags = 'backend,databases,scalability'. We count how many of the career's tags appear in the student's interests and compute a match percentage. This is the core of the recommendation algorithm."),

    h2("3.4 Skill Table"),
    h3("Purpose"),
    p("Every technology or domain concept that might be required for a career (Java, Spring Boot, REST APIs, PostgreSQL, etc.)."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("name (String, Unique) — 'Java', 'Spring Boot', 'PostgreSQL', etc."),
    bul("category (String) — 'Programming Language', 'Framework', 'Database', 'DevOps', etc."),
    bul("description (String) — What this skill is and why it matters"),
    bul("difficulty_level (Enum: BEGINNER, INTERMEDIATE, ADVANCED) — Estimated learning difficulty"),
    bul("created_at (LocalDateTime)"),
    h3("Relationships"),
    bul("Many-to-Many with Career through career_skills junction table"),
    bul("One-to-Many with Resource"),
    bul("One-to-Many with UserSkillProgress"),
    h3("Key Interview Points"),
    p("Skills are the basic building blocks. Every career requires a set of skills. Every skill can have multiple resources (videos, courses, articles) pointing to it. When a student picks a career, we show them which skills are required and which ones they already know."),

    h2("3.5 career_skills Junction Table"),
    h3("Purpose"),
    p("Links careers to skills in a many-to-many relationship. One career requires many skills, and one skill might be required by many careers."),
    h3("Columns"),
    bul("career_id (Foreign Key) — Reference to Career"),
    bul("skill_id (Foreign Key) — Reference to Skill"),
    bul("is_required (Boolean) — True if this skill is required for the career"),
    bul("importance_level (Integer) — 1-5 ranking of how important this skill is"),
    h3("Key Interview Points"),
    p("This is a pure junction table with no additional data except the foreign keys. When we want to show a student their skill gap for Java Backend Developer, we retrieve all rows where career_id matches and then check which of those skills are in their known_skill_names list."),

    h2("3.6 Resource Table"),
    h3("Purpose"),
    p("Learning materials (videos, courses, tutorials, articles) associated with skills or careers."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("title (String) — 'Java Full Course by Telusko', 'Spring Boot Tutorial', etc."),
    bul("type (Enum: VIDEO, PLAYLIST, COURSE, ARTICLE, GITHUB) — Type of resource"),
    bul("url (String) — The link to the resource"),
    bul("skill_id (Foreign Key) — Which skill this teaches"),
    bul("career_id (Foreign Key, Nullable) — Optional: if linked to a specific career"),
    bul("created_at (LocalDateTime)"),
    h3("Key Interview Points"),
    p("When a student lands on a Skill Detail page, we fetch all resources where skill_id matches. The frontend then renders them as cards with YouTube thumbnails for videos or course badges for courses. If career_id is set, the resource is only shown in that career's context."),

    h2("3.7 Resume Table"),
    h3("Purpose"),
    p("Stores uploaded resume documents and extracted text."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("user_id (Foreign Key) — Which user uploaded this"),
    bul("filename (String) — Original filename of the PDF"),
    bul("extracted_text (Text, very large) — All text extracted from the PDF"),
    bul("uploaded_at (LocalDateTime) — When the file was uploaded"),
    bul("stored_file_path (String) — Path to the file on disk"),
    h3("Relationships"),
    bul("One-to-Many with ResumeAnalysis — One resume can be analyzed multiple times"),
    h3("Key Interview Points"),
    p("The extraction happens via Apache PDFBox when the file is uploaded. The extracted_text is stored so we don't have to re-extract it every time. This text is what gets sent to the Gemini AI for analysis."),

    h2("3.8 ResumeAnalysis Table"),
    h3("Purpose"),
    p("Stores the AI-generated analysis of a resume."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("resume_id (Foreign Key) — Which resume was analyzed"),
    bul("ats_score (Integer) — 0-100 ATS compatibility score"),
    bul("summary (String) — AI-generated summary of strengths and weaknesses"),
    bul("strengths (String) — JSON array of identified strengths"),
    bul("improvements (String) — JSON array of suggested improvements"),
    bul("missing_sections (String) — JSON array of missing resume sections"),
    bul("suggested_skills (String) — JSON array of skills to add"),
    bul("job_match_score (Integer, Nullable) — 0-100 match score if JD was provided"),
    bul("matched_keywords (String, Nullable) — JSON array of JD keywords found in resume"),
    bul("missing_keywords (String, Nullable) — JSON array of JD keywords NOT found"),
    bul("analyzed_at (LocalDateTime)"),
    h3("Key Interview Points"),
    p("The analysis is stored as JSON strings in text columns. When the frontend displays it, we parse these strings back into JavaScript objects. If a job description was provided during analysis, job_match_score and the keyword arrays will be populated; otherwise they're null."),

    h2("3.9 UserSkillProgress Table"),
    h3("Purpose"),
    p("Tracks which skills a student has marked as completed or is currently learning, in the context of a specific career."),
    h3("Columns"),
    bul("id (Long, Primary Key)"),
    bul("user_id (Foreign Key) — Which user"),
    bul("skill_id (Foreign Key) — Which skill"),
    bul("career_id (Foreign Key) — In the context of which career"),
    bul("status (Enum: LEARNING, COMPLETED) — Current status"),
    bul("marked_at (LocalDateTime) — When this was marked"),
    h3("Unique Constraint"),
    p("Composite unique on (user_id, skill_id, career_id). This means a user can independently mark Spring Boot as COMPLETED for Java Backend Developer and LEARNING for Full Stack Developer without conflict."),
    h3("Key Interview Points"),
    p("When we compute the 'readiness percentage' for a career, we count how many records have status=COMPLETED and divide by the total skill count for that career. This is computed dynamically, not stored."),

    h2("3.10 EmailVerificationToken & PasswordResetToken Tables"),
    h3("Purpose"),
    p("Store one-time-use tokens for email verification and password reset flows."),
    h3("Columns (EmailVerificationToken)"),
    bul("id (Long, Primary Key)"),
    bul("user_id (Foreign Key) — Which user owns this token"),
    bul("token (String, Unique) — UUID value of the token"),
    bul("expires_at (LocalDateTime) — 24 hours from creation"),
    bul("used (Boolean) — True after the token is clicked"),
    bul("created_at (LocalDateTime)"),
    h3("Key Interview Points"),
    p("These are stateless tokens. When a user clicks the verification link, we receive the token as a URL parameter, look it up in the database, check if it's expired and not already used, and if all checks pass, we set the user's isVerified to true and mark the token as used. For password reset, the process is identical but the token has a 30-minute expiry instead of 24 hours."),
    sp(),pb(),

    // PART 4
    h1("Part 4: Authentication & Security Flow"),
    h2("4.1 Registration Flow"),
    h3("What Happens When a Student Registers"),
    bul("User submits: email, password, full name"),
    bul("Backend validates: email not already in use"),
    bul("Backend hashes password using BCrypt with 10 rounds (slow on purpose)"),
    bul("New User record created with isVerified = false, role = USER"),
    bul("EmailVerificationToken created with UUID, 24-hour expiry"),
    bul("HTML email sent to user's email address with verification link"),
    bul("Frontend receives 201 Created response"),
    h3("Code Path"),
    code("POST /api/auth/register → AuthController.register() → UserService.registerUser() → UserRepository.save() → EmailService.sendVerificationEmail()"),
    h2("4.2 Email Verification Flow"),
    h3("What Happens When User Clicks Email Link"),
    p("User clicks link like: https://frontend.com/verify-email?token=uuid-here"),
    p("Frontend extracts token from URL, calls /api/auth/verify-email?token=xxx"),
    p("Backend receives token, looks it up in database"),
    p("Validation: token exists + used=false + not expired + user exists"),
    p("If valid: set user.isVerified=true, set token.used=true, save both"),
    p("Return success response"),
    h3("Edge Case Handling"),
    p("React StrictMode double-fires effects. So verification might be called twice. Backend handles this: if token.used is already true BUT user.isVerified is already true, return success anyway. Frontend also uses useRef to guard against the second call."),
    h2("4.3 Login Flow"),
    h3("What Happens When Student Logs In"),
    bul("User submits: email, password"),
    bul("Backend retrieves User by email"),
    bul("If user not found: return 404 with 'User not found'"),
    bul("Check if user.isVerified is true: Boolean.FALSE.equals(user.getIsVerified())"),
    bul("If false: return 403 with 'EMAIL_NOT_VERIFIED' error"),
    bul("If verified: compare password using BCrypt.matches(inputPassword, storedHash)"),
    bul("If match: create JWT token with user.id and role inside"),
    bul("Return token to frontend"),
    h3("Why Boolean.FALSE.equals()?"),
    p("The isVerified field is Boolean (wrapper class), not boolean (primitive). Using Boolean.FALSE.equals() is null-safe. If the field is null (legacy accounts before verification feature), it doesn't throw NullPointerException. If the field is null, the check returns false, meaning the user is allowed through. This handles backward compatibility gracefully."),
    h2("4.4 JWT Token Structure"),
    h3("What's Inside the JWT"),
    code("Header: {alg: 'HS256', typ: 'JWT'}"),
    code("Payload: {sub: userId, role: 'USER', iat: timestamp, exp: timestamp + 24 hours}"),
    code("Signature: HMAC-SHA256(header+payload, secret)"),
    h3("Token Lifecycle"),
    bul("Created at login, returned to frontend"),
    bul("Frontend stores in localStorage"),
    bul("Axios interceptor attaches to every request: Authorization: Bearer <token>"),
    bul("Backend custom JWT filter intercepts request, extracts token"),
    bul("Filter validates signature, checks expiration"),
    bul("If valid, request proceeds; if invalid, returns 401"),
    bul("Token expires after 24 hours; user must log in again"),
    h2("4.5 Password Reset Flow"),
    h3("Step 1: Request Reset"),
    p("User submits email on forgot password page"),
    p("Backend creates PasswordResetToken with UUID, 30-minute expiry"),
    p("Email sent with reset link: https://frontend.com/reset-password?token=xxx"),
    h3("Step 2: Submit New Password"),
    p("User clicks link, fills in new password"),
    p("Frontend posts to /api/auth/reset-password with token and newPassword"),
    p("Backend validates token (exists, not used, not expired)"),
    p("If valid: hash new password, update user, mark token as used"),
    p("Return success"),
    h2("4.6 Spring Security Configuration"),
    h3("How It's Set Up"),
    code("@EnableWebSecurity on main class"),
    code("SecurityFilterChain bean defines what needs auth and what doesn't"),
    code("permitAll() on public endpoints: /register, /login, /verify-email, etc."),
    code("Stateless session creation (no session cookies)"),
    code("Custom JWT filter inserted before UsernamePasswordAuthenticationFilter"),
    code("CORS configured to allow frontend origin"),
    h3("Example Endpoint Protection"),
    code("@GetMapping('/api/user/profile') requires: authenticated + role=USER (implicit)"),
    code("@PostMapping('/api/admin/career') requires: authenticated + role=ADMIN (explicit)"),
    sp(),pb(),

    // PART 5
    h1("Part 5: Core Service Classes - Line by Line"),
    h2("5.1 RecommendationService"),
    h3("Purpose"),
    p("Implements the weighted scoring algorithm that matches students to careers."),
    h3("Key Method: getRecommendations(userId)"),
    code("1. Fetch user and their profile from database"),
    code("2. Split profile.interestAreas into List<String> by comma"),
    code("3. Same for workStyle and goals"),
    code("4. Fetch ALL careers from database"),
    code("5. For each career:"),
    code("   a. interestScore = (career.interestTags intersection with user interests) / (career.interestTags count) * 40"),
    code("   b. workStyleScore = (similar) * 30"),
    code("   c. goalScore = (similar) * 20"),
    code("   d. educationBonus = user.educationLevel != null ? 10 : 0"),
    code("   e. totalScore = interestScore + workStyleScore + goalScore + educationBonus"),
    code("6. Filter out careers with score 0"),
    code("7. Sort by score descending"),
    code("8. Take top 10, return"),
    h3("Why This Algorithm?"),
    p("The proportional matching (intersection / total) means a career with 3 tags that all match is worth more than a career with 10 tags that partially match. Fixed weights (40, 30, 20, 10) reflect importance: interests matter most, then work style, then goals, then education. This is a design choice, not a machine learning model."),
    h3("Interview Talking Point"),
    p("Explain that this is content-based matching, not collaborative filtering. We don't need historical data to make recommendations — we can recommend to new users immediately because we're matching their attributes against career attributes. The weights reflect business logic about what matters for career fit."),

    h2("5.2 SmartOnboardingService"),
    h3("Purpose"),
    p("Takes the list of recommended careers and adds AI-generated explanations."),
    h3("Key Method: getSmartRecommendations(List<CareerRecommendation>)"),
    code("1. For each of top 3 careers:"),
    code("2.   Create prompt: 'Career: {name}. User interests: {interests}. Write 2-sentence explanation why this matches.'"),
    code("3.   Call Gemini API with prompt"),
    code("4.   Parse response as String"),
    code("5.   Add explanation to CareerRecommendation object"),
    code("6. Return enriched list"),
    h3("Why Not Just the Algorithm?"),
    p("The algorithm gives a number, but students want to understand why. Gemini generates human-readable context that interprets the match percentage and explains it in terms of their specific interests. A student sees: '78% match — Your interest in databases and scalability aligns well with this role's focus on backend infrastructure.'"),

    h2("5.3 SkillGapService"),
    h3("Purpose"),
    p("Identifies which skills a student needs to learn for a chosen career."),
    h3("Key Method: getSkillGap(userId, careerId)"),
    code("1. Fetch user profile (has knownSkillNames)"),
    code("2. Fetch career, including all linked skills via Many-to-Many relationship"),
    code("3. Split user.knownSkillNames into List<String>"),
    code("4. For each career skill:"),
    code("   if (skill.name.toLowerCase() in knownSkillNames.map(s => s.toLowerCase()))"),
    code("     add to 'possessed' list"),
    code("   else"),
    code("     add to 'missing' list"),
    code("5. Return SkillGapDTO with both lists"),
    h3("Why Case-Insensitive?"),
    p("User might type 'spring boot' in onboarding. Career has it as 'Spring Boot'. We compare lowercase versions so they match. This is more user-friendly than requiring exact case matching."),

    h2("5.4 AiAnalysisService - The Learning Order Engine (Two-Stage)"),
    h3("Purpose"),
    p("Generates a prerequisite-aware learning roadmap for missing skills."),
    h3("Key Method: generateLearningOrder(careerId, missingSkillNames)"),
    code("STAGE 1: AI GENERATION"),
    code("1. Fetch career.title"),
    code("2. Create prompt with 9 ordering rules (languages before frameworks, etc.)"),
    code("3. Prompt: 'Career: {title}. Order these skills: {skillNames}. Return JSON array of skill names in learning order.'"),
    code("4. Call Gemini API"),
    code("5. Parse response JSON into List<String>"),
    code(""),
    code("STAGE 2: PREREQUISITE ENFORCEMENT"),
    code("6. Call enforcePrerequisites(orderedList)"),
    code("7. In enforcePrerequisites:"),
    code("   a. Create Map<String, String> where key=prerequisite, value=dependent"),
    code("   b. Map includes: 'Django' -> 'Django REST Framework', 'Spring Framework' -> 'Spring Boot', etc."),
    code("   c. Loop through map:"),
    code("      - Find index of prerequisite in list"),
    code("      - Find index of dependent in list"),
    code("      - If prerequisite index > dependent index: move prerequisite to just before dependent"),
    code("   d. Repeat until no changes in a full pass"),
    code("8. Final pass: move any skill containing 'Docker', 'Git', 'CI/CD', etc. to end"),
    code("9. Return enforced list"),
    h3("Why Two Stages?"),
    p("Stage 1 uses the AI model's knowledge of general learning sequences. Stage 2 enforces absolute rules for known dependencies. This hybrid approach combines flexibility (the AI can handle unknown careers) with correctness (we guarantee known dependencies are respected). Neither stage alone is sufficient."),
    h3("Interview Talking Point"),
    p("'The first time we built this, we just used Gemini. It got the ordering right about 70% of the time. For less common careers like Blockchain Developer, it was much worse — maybe 40% correct. We added the post-processing stage with a hardcoded prerequisite map, and now we're at 100% correctness because we're enforcing rules we know are true. The trade-off is we need to manually maintain that map as new skills are added.'"),

    h2("5.5 ResumeAnalysisService"),
    h3("Purpose"),
    p("Extracts text from PDF and sends to AI for analysis."),
    h3("Key Method: analyzeResume(resumeText, jobDescription)"),
    code("1. Create prompt with JSON schema"),
    code("2. If jobDescription is provided:"),
    code("   'Analyze this resume against this job description. Return: {ats_score: number, summary: string, strengths: [string], improvements: [string], matched_keywords: [string], missing_keywords: [string], ...}'"),
    code("3. Else:"),
    code("   'Analyze this resume. Return: {ats_score: number, summary: string, strengths: [string], ..., job_match_score: null, matched_keywords: null, ...}'"),
    code("4. Set maxOutputTokens=8192 (resume analysis is verbose)"),
    code("5. Call Gemini API"),
    code("6. Response comes back as string"),
    code("7. Strip markdown code fences (```json ... ```)"),
    code("8. Parse as JSON"),
    code("9. Store in ResumeAnalysis entity"),
    h3("Why maxOutputTokens=8192?"),
    p("A complete resume analysis includes ATS score, summary, multiple strengths, multiple improvements, missing sections, suggested skills, and optionally keyword lists. Keeping the token limit too low causes Gemini to cut off the response mid-JSON, making it unparseable. 8192 gives plenty of room."),

    h2("5.6 EmailService"),
    h3("Purpose"),
    p("Sends emails through Gmail SMTP."),
    h3("Key Method: sendVerificationEmail(user, token)"),
    code("1. Create SimpleMailMessage"),
    code("2. Set from: spring.mail.username (Gmail address)"),
    code("3. Set to: user.email"),
    code("4. Set subject: 'Verify your AI Career Guidance Agent email'"),
    code("5. Build HTML body with verification link: '{frontend.url}/verify-email?token={token}'"),
    code("6. Call javaMailSender.send(message)"),
    code("7. Log success/failure"),
    h3("Gmail Configuration"),
    code("spring.mail.host = smtp.gmail.com"),
    code("spring.mail.port = 587"),
    code("spring.mail.username = your-gmail@gmail.com"),
    code("spring.mail.password = (Gmail App Password, not your actual password)"),
    code("spring.mail.properties.mail.smtp.auth = true"),
    code("spring.mail.properties.mail.smtp.starttls.enable = true"),
    h3("Important Security Note"),
    p("The Gmail password is NOT your actual Gmail password. You create an 'App Password' in Gmail settings. This 16-character password is used only for this application. If it leaks, you can delete it without changing your main Gmail password."),

    h2("5.7 PasswordResetService"),
    h3("Purpose"),
    p("Handles forgot password flow."),
    h3("Key Method: initiatePasswordReset(email)"),
    code("1. Fetch user by email"),
    code("2. If not found: return successfully anyway (don't leak that email isn't registered)"),
    code("3. Create UUID token"),
    code("4. Create PasswordResetToken with 30-minute expiry"),
    code("5. Save to database"),
    code("6. Send email with reset link"),
    code("7. Return success"),
    h3("Key Method: resetPassword(token, newPassword)"),
    code("1. Fetch PasswordResetToken by token string"),
    code("2. Validate: exists, used=false, not expired"),
    code("3. If invalid: return 400 'Invalid or expired token'"),
    code("4. Hash new password with BCrypt"),
    code("5. Update user.password"),
    code("6. Set token.used=true"),
    code("7. Save both changes"),
    code("8. Return success"),
    sp(),pb(),

    // PART 6
    h1("Part 6: Controller Classes - Request Handling"),
    h2("6.1 AuthController"),
    h3("Purpose"),
    p("Handles all authentication endpoints: register, login, verify email, forgot password, reset password."),
    h3("Endpoints"),
    bul("POST /api/auth/register"),
    bul("POST /api/auth/login"),
    bul("GET /api/auth/verify-email?token=xxx"),
    bul("POST /api/auth/forgot-password"),
    bul("POST /api/auth/reset-password"),
    bul("POST /api/auth/resend-verification"),
    h3("Code Flow Example: Login"),
    code("@PostMapping('/login')"),
    code("public ResponseEntity<?> login(@RequestBody LoginRequest req) {"),
    code("  try {"),
    code("    User user = userService.authenticateUser(req.getEmail(), req.getPassword());"),
    code("    String token = jwtTokenProvider.generateToken(user.getId(), user.getRole());"),
    code("    return ResponseEntity.ok(new LoginResponse(token, user.getId(), user.getRole()));"),
    code("  } catch (UserNotFoundException | IncorrectPasswordException e) {"),
    code("    return ResponseEntity.status(401).body(new ErrorResponse(e.getMessage()));"),
    code("  }"),
    code("}"),

    h2("6.2 RecommendationController"),
    h3("Purpose"),
    p("GET endpoint for the recommendation flow."),
    h3("Endpoint"),
    code("GET /api/user/recommendations"),
    h3("Code Flow"),
    code("1. Extract userId from JWT (SecurityContextHolder)"),
    code("2. Check if user has completed onboarding (check UserProfile exists)"),
    code("3. Call recommendationService.getRecommendations(userId)"),
    code("4. Call smartOnboardingService to add explanations"),
    code("5. Return list of CareerRecommendationDTO"),
    h3("Why Check Onboarding?"),
    p("If a user hasn't filled out the 6-step form, there's no profile data to score against. Returning recommendations with no data would be meaningless. The endpoint should return 400 Bad Request with 'Please complete onboarding first'."),

    h2("6.3 CareerController"),
    h3("Endpoints"),
    bul("GET /api/careers — List all careers with pagination"),
    bul("GET /api/careers/{id} — Details of one career"),
    bul("GET /api/careers/{id}/skill-gap — Skill gap for this career (requires user authenticated)"),
    bul("GET /api/careers/{id}/learning-order — Skill learning order (requires user authenticated)"),
    h3("Example: Skill Gap Endpoint"),
    code("@GetMapping('/{careerId}/skill-gap')"),
    code("public ResponseEntity<?> getSkillGap(@PathVariable Long careerId) {"),
    code("  Long userId = getCurrentUserId(); // from JWT"),
    code("  SkillGapDTO gap = skillGapService.getSkillGap(userId, careerId);"),
    code("  return ResponseEntity.ok(gap);"),
    code("}"),

    h2("6.4 ResumeController"),
    h3("Endpoints"),
    bul("POST /api/resume/upload — Upload and extract PDF"),
    bul("GET /api/resume/my-resumes — List resumes for logged-in user"),
    bul("POST /api/resume/{id}/analyze — Analyze a resume"),
    h3("Example: Upload Endpoint"),
    code("@PostMapping('/upload')"),
    code("public ResponseEntity<?> uploadResume(@RequestParam('file') MultipartFile file) {"),
    code("  Long userId = getCurrentUserId();"),
    code("  Resume resume = resumeService.uploadResume(userId, file);"),
    code("  return ResponseEntity.status(201).body(new ResumeResponse(resume.getId()));"),
    code("}"),

    h2("6.5 AdminController"),
    h3("Endpoints"),
    bul("GET /api/admin/stats — Counts of users, careers, skills, resumes"),
    bul("POST /api/admin/career — Create new career"),
    bul("PUT /api/admin/career/{id} — Update career"),
    bul("DELETE /api/admin/career/{id} — Delete career"),
    bul("Similar endpoints for skills, resources, AI tools"),
    h3("Authorization"),
    p("All /api/admin/** endpoints check for ADMIN role via Spring Security authorization rule. Non-admin users get 403 Forbidden."),
    sp(),pb(),

    // PART 7
    h1("Part 7: Entity Classes & JPA Relationships"),
    h2("7.1 User Entity"),
    code("@Entity"),
    code("@Table(name = 'users')"),
    code("public class User {"),
    code("  @Id"),
    code("  @GeneratedValue(strategy = GenerationType.IDENTITY)"),
    code("  private Long id;"),
    code("  "),
    code("  @Column(unique = true, nullable = false)"),
    code("  private String email;"),
    code("  "),
    code("  @Column(nullable = false)"),
    code("  private String password; // BCrypt hashed"),
    code("  "),
    code("  private String fullName;"),
    code("  "),
    code("  @Enumerated(EnumType.STRING)"),
    code("  @Column(nullable = false)"),
    code("  private Role role = Role.USER; // USER or ADMIN"),
    code("  "),
    code("  @Column(columnDefinition = 'BOOLEAN DEFAULT false')"),
    code("  private Boolean isVerified = false; // NULL for old accounts"),
    code("  "),
    code("  @OneToOne(mappedBy = 'user', cascade = CascadeType.ALL)"),
    code("  private UserProfile profile;"),
    code("  "),
    code("  @OneToMany(mappedBy = 'user', cascade = CascadeType.ALL)"),
    code("  private List<Resume> resumes;"),
    code("  "),
    code("  @OneToMany(mappedBy = 'user', cascade = CascadeType.ALL)"),
    code("  private List<UserSkillProgress> progress;"),
    code("}"),
    h3("Key Annotations Explained"),
    bul("@Entity — This class maps to a database table"),
    bul("@Table(name='users') — Table name in database"),
    bul("@Id — Primary key"),
    bul("@GeneratedValue(GenerationType.IDENTITY) — Auto-increment ID"),
    bul("@Column(unique=true) — This column has unique constraint"),
    bul("@Enumerated(EnumType.STRING) — Save enum as string, not integer"),
    bul("@OneToOne(mappedBy='user') — Bidirectional relationship; User side is the non-owning side"),
    bul("@OneToMany(mappedBy='user', cascade=CascadeType.ALL) — When user is deleted, delete all related records"),

    h2("7.2 Career-Skill Many-to-Many Relationship"),
    h3("Career Entity (owning side)"),
    code("@Entity"),
    code("public class Career {"),
    code("  // ... other fields ..."),
    code("  "),
    code("  @ManyToMany(cascade = CascadeType.PERSIST)"),
    code("  @JoinTable("),
    code("    name = 'career_skills',"),
    code("    joinColumns = @JoinColumn(name = 'career_id'),"),
    code("    inverseJoinColumns = @JoinColumn(name = 'skill_id')"),
    code("  )"),
    code("  private Set<Skill> skills = new HashSet<>();"),
    code("}"),
    h3("Skill Entity (non-owning side)"),
    code("@Entity"),
    code("public class Skill {"),
    code("  // ... other fields ..."),
    code("  "),
    code("  @ManyToMany(mappedBy = 'skills')"),
    code("  private Set<Career> careers = new HashSet<>();"),
    code("}"),
    h3("Why Many-to-Many?"),
    p("One career requires many skills. One skill might be required by many careers. A junction table (career_skills) in the database represents this relationship. The owning side (Career) defines the @JoinTable. The non-owning side (Skill) uses mappedBy to reference the relationship."),

    h2("7.3 Bidirectional Relationship - The Serialization Problem"),
    h3("What Goes Wrong"),
    code("If Career has @OneToMany List<Resource> resources"),
    code("And Resource has @ManyToOne Career career"),
    code("When serializing Career to JSON:"),
    code("- Career includes resources"),
    code("- Each Resource includes career"),
    code("- Each Career includes resources again..."),
    code("- INFINITE LOOP! StackOverflowError!"),
    h3("The Solution"),
    code("@Entity"),
    code("public class Career {"),
    code("  @OneToMany(mappedBy = 'career')"),
    code("  @JsonManagedReference"),
    code("  private List<Resource> resources;"),
    code("}"),
    code(""),
    code("@Entity"),
    code("public class Resource {"),
    code("  @ManyToOne"),
    code("  @JsonBackReference"),
    code("  private Career career;"),
    code("}"),
    h3("How It Works"),
    p("@JsonManagedReference tells Jackson 'serialize the resources normally'. @JsonBackReference tells Jackson 'don't serialize the career field to avoid infinite loop'. The database still has the foreign key; we're just controlling JSON serialization."),
    sp(),pb(),

    // PART 8
    h1("Part 8: Key Algorithms - Deep Dive"),
    h2("8.1 Weighted Recommendation Algorithm"),
    h3("Conceptual Example"),
    p("Student profile: interests=['backend','databases','scalability'], workStyle=['independent','analytical'], goals=['growth','salary'], education='Bachelor'"),
    p("Career: Java Backend Developer with interests=['backend','databases','scalability'], workStyle=['independent','analytical','collaborative'], goals=['growth','learning']"),
    h3("Scoring"),
    code("Interest Match:"),
    code("  Career interests: ['backend','databases','scalability'] (3 total)"),
    code("  Student interests: ['backend','databases','scalability']"),
    code("  Matching: all 3 match"),
    code("  Score: 3/3 * 40 = 40 points"),
    code(""),
    code("WorkStyle Match:"),
    code("  Career workStyle: ['independent','analytical','collaborative'] (3 total)"),
    code("  Student workStyle: ['independent','analytical']"),
    code("  Matching: 2 match"),
    code("  Score: 2/3 * 30 = 20 points"),
    code(""),
    code("Goal Match:"),
    code("  Career goals: ['growth','learning'] (2 total)"),
    code("  Student goals: ['growth','salary']"),
    code("  Matching: 1 matches"),
    code("  Score: 1/2 * 20 = 10 points"),
    code(""),
    code("Education Bonus: 10 points (student has education level)"),
    code(""),
    code("Total: 40 + 20 + 10 + 10 = 80 points (out of ~100)"),
    h3("Why Proportional?"),
    p("If a career only has 2 interest tags and both match, it gets 2/2 * 40 = 40 points. If a career has 10 tags and only 4 match, it gets 4/10 * 40 = 16 points. This prevents 'noise' — careers with many tags that partially align don't score higher than careers with fewer tags that align perfectly. This is a deliberate design choice."),

    h2("8.2 Skill Ordering Algorithm - Detailed Example"),
    h3("Input"),
    p("Career: Java Backend Developer, Missing skills: [Spring Framework, Java, Docker, Rest APIs, Spring Boot, JWT, Database Design]"),
    h3("Stage 1: AI Generation"),
    code("Prompt sent to Gemini:"),
    code("\"Career: Java Backend Developer\""),
    code("\"Order these skills for optimal learning:\""),
    code("\"[Spring Framework, Java, Docker, REST APIs, Spring Boot, JWT, Database Design]\""),
    code("\"\""),
    code("\"Rules:\""),
    code("\"1. Programming languages come before frameworks\""),
    code("\"2. Core concepts before applications\""),
    code("\"3. Parent frameworks before child modules\""),
    code("\"4. DevOps tools come last\""),
    code("\"\""),
    code("\"Return only a JSON array of skill names in the correct order.\""),
    code(""),
    code("Gemini response: [\"Java\", \"Database Design\", \"REST APIs\", \"Spring Framework\", \"Spring Boot\", \"JWT\", \"Docker\"]"),
    h3("Stage 2: Prerequisite Enforcement"),
    code("Prerequisites map contains: 'Spring Framework' -> 'Spring Boot'"),
    code("Current order: [\"Java\", \"Database Design\", \"REST APIs\", \"Spring Framework\", \"Spring Boot\", \"JWT\", \"Docker\"]"),
    code("Indexes: Java=0, Spring Framework=3, Spring Boot=4, Docker=6"),
    code(""),
    code("Check 'Spring Framework' -> 'Spring Boot':"),
    code("  Spring Framework at index 3, Spring Boot at index 4"),
    code("  3 < 4: Spring Framework comes before Spring Boot ✓ CORRECT"),
    code(""),
    code("No violations detected. Move to final pass: push DevOps (Docker) to end."),
    code("Current: [Java, Database Design, REST APIs, Spring Framework, Spring Boot, JWT, Docker]"),
    code("Docker is already last ✓"),
    code(""),
    code("Final output: [\"Java\", \"Database Design\", \"REST APIs\", \"Spring Framework\", \"Spring Boot\", \"JWT\", \"Docker\"]"),
    h3("What if AI Gets It Wrong?"),
    code("Hypothetical bad AI response: [\"Spring Boot\", \"Java\", \"REST APIs\", \"Spring Framework\", \"Database Design\", \"JWT\", \"Docker\"]"),
    code(""),
    code("Check 'Spring Framework' -> 'Spring Boot':"),
    code("  Spring Framework at index 3, Spring Boot at index 0"),
    code("  3 > 0: Spring Framework comes AFTER Spring Boot ✗ WRONG"),
    code("  Action: Move Spring Framework to position 2 (just before Spring Boot)"),
    code("  New list: [\"Java\", \"Spring Framework\", \"Spring Boot\", \"REST APIs\", \"Database Design\", \"JWT\", \"Docker\"]"),
    code(""),
    code("Continue checking all prerequisites until no changes..."),
    code("Final output: [\"Java\", \"Database Design\", \"REST APIs\", \"Spring Framework\", \"Spring Boot\", \"JWT\", \"Docker\"]"),
    h3("Interview Talking Point"),
    p("'The challenge was that large language models don't consistently enforce ordering constraints. We found that Gemini would sometimes put Spring Boot before Spring Framework, or REST APIs before the language to implement them in. Rather than trying to fix the prompt (which never worked perfectly), we added a deterministic post-processing step. We maintain a list of known dependencies and enforce them programmatically. This guarantees correctness while letting the AI provide contextual knowledge. It's the best of both worlds.'"),
    sp(),pb(),

    // PART 13
    h1("Part 13: Common Interview Questions & Answers"),
    h2("13.1 'Tell me about your project'"),
    p("AI Career Guidance Agent is a full-stack career guidance platform for students. The core problem it solves: students want to start a tech career but don't know which one, which skills to learn, or if their resume is ready. Most tools solve one piece. AI Career Guidance Agent solves all three plus tracks learning progress, all in one place."),
    p("The tech stack: React.js frontend with Vite, Java Spring Boot backend, PostgreSQL database, and Google Gemini AI for generating explanations and analyzing resumes."),

    h2("13.2 'How does the career recommendation algorithm work?'"),
    p("It's a weighted content-based matching system. During onboarding, we collect the student's interests (like 'backend', 'databases'), work style preferences ('independent', 'collaborative'), career goals, and education level. We compare these against every career in the database. Each dimension gets a weight: interests 40%, work style 30%, goals 20%, education 10%. We use proportional matching — if a career's 3 interest tags all match the student's interests, it scores 3/3 * 40 = 40 points. If a career has 10 tags and only 4 match, it scores 4/10 * 40 = 16 points. This prevents careers with many loosely relevant tags from scoring higher than careers with fewer highly relevant tags."),

    h2("13.3 'What's unique about the skill ordering engine?'"),
    p("Most recommendation systems either rely purely on AI models or purely on manually curated prerequisite graphs. Both have problems. AI is flexible but inconsistent — it gets the ordering right 70% of the time, worse for less common career paths. Manual graphs are reliable but require constant maintenance."),
    p("We use a hybrid two-stage approach. Stage 1: Gemini generates an ordering based on the career and skills. Stage 2: A Java method called enforcePrerequisites runs through a static map of 30+ known dependencies and corrects any violations through iterative position swapping. This combination gives us the flexibility of AI with the correctness guarantee of rule enforcement. We get 100% correctness on known dependencies while still handling new or uncommon career paths gracefully."),

    h2("13.4 'Walk me through the registration and verification flow'"),
    p("User registers with email, password, and name. Backend validates the email isn't already in use, hashes the password with BCrypt (10 rounds, intentionally slow), creates a User record with isVerified=false, generates a UUID verification token with a 24-hour expiry, and sends an HTML email with a verification link."),
    p("When the user clicks the link, the frontend extracts the token and calls the verify endpoint. Backend checks: token exists, hasn't been used before, and hasn't expired. If all checks pass, we set user.isVerified=true and mark the token as used."),
    p("On login, we check Boolean.FALSE.equals(user.getIsVerified()). This is null-safe — if the field is null (legacy accounts), the user is allowed through. This handles backward compatibility if the feature was added to an existing system."),
    p("We use a useRef guard on the frontend to prevent the verification from being called twice (React's StrictMode double-fires effects), and the backend also returns success if the token is already used but the user is already verified, so even if both calls go through, the user sees success."),

    h2("13.5 'How do you handle the resume analysis?'"),
    p("When a student uploads a PDF, Apache PDFBox extracts all the text. We store the extracted text so we don't have to re-extract every time."),
    p("When the student triggers analysis, we send the extracted text to Gemini with a structured prompt specifying exact JSON output: ATS score, summary, strengths list, improvements list, missing sections, and suggested skills. If they provide a job description, we add fields for job match score and keyword lists."),
    p("We set maxOutputTokens=8192 because a complete analysis is verbose. The response comes back as a string. We strip any markdown code fences, parse it as JSON, and store it in the database."),
    p("The frontend then parses this JSON and renders it as: a score ring, horizontal bar charts for strengths/improvements, and text sections for other feedback."),

    h2("13.6 'What's the most challenging part of building this?'"),
    p("The skill ordering was the most challenging. Initially, we just asked Gemini to order skills. It worked maybe 70% of the time. The problem was more acute for less-documented career paths — blockchain developer skills might get ordered incorrectly 40% of the time because there's less sequential learning content available in the training data."),
    p("We tried dozens of prompt variations. Nothing consistently worked. So we pivoted to the hybrid approach: use AI for contextual knowledge, but enforce hard rules programmatically. Building the prerequisite map (30+ skill pairs) took time, but it guarantees correctness."),
    p("The other challenging part was handling bidirectional JPA relationships without infinite JSON serialization loops. You need @JsonManagedReference and @JsonBackReference in the right places, and if you get it wrong, you discover it through a StackOverflowError at runtime."),

    h2("13.7 'How do you secure passwords?'"),
    p("We never store plain text passwords. When a user sets a password, we hash it with BCrypt using 10 rounds. BCrypt is intentionally slow (takes ~100-200ms to hash) so that even if someone gets the password file, brute-forcing is computationally expensive."),
    p("When a user logs in, we take their input password, hash it with BCrypt using the same salt that was used for storage, and compare the hashes. If they match, the password is correct."),
    p("For password reset, the process is similar: we create a single-use UUID token with a 30-minute expiry. When they submit a new password, we validate the token, hash the new password, and save it."),

    h2("13.8 'How does the admin panel work?'"),
    p("All /api/admin/** endpoints are protected by a Spring Security rule that checks for the ADMIN role. Non-admin users get a 403 Forbidden response."),
    p("Admins can create, read, update, and delete careers, skills, resources, and AI tools. There's a skill-career linking endpoint that accepts a career ID and a list of skill IDs and updates the junction table."),
    p("We have a stats endpoint that returns counts of users, careers, skills, and resumes in a single query. This dashboard gives admins visibility into the platform's content."),

    h2("13.9 'How do you handle edge cases in verification?'"),
    p("React's StrictMode double-fires effects in development. So the verification endpoint might be called twice with the same token. Our solution: if the token has already been used but the user is already verified, return success anyway. This way the user doesn't see an error for what is actually a successful verification."),
    p("On the frontend, we added a useRef guard to prevent the second call from even happening. useRef persists across renders without causing re-renders, so we check hasCalled before making the API call, and if it's already true, we skip the call."),
    p("This combination of frontend guard + backend graceful handling means the user has a smooth experience regardless of whether the function runs once or twice."),

    h2("13.10 'Why use JWT instead of sessions?'"),
    p("JWT is stateless. Each request includes the token. The server doesn't store session state. This is more scalable — you can run multiple instances of the backend and any instance can validate any token because validation just requires checking the signature."),
    p("With sessions, the server stores session data and the client gets a session cookie. If you scale to multiple backend instances, you need sticky sessions or a shared session store, adding complexity."),
    p("The trade-off is that JWT tokens can't be revoked immediately (they're valid until expiry). We handle this with a 24-hour expiry. If a token is compromised, the damage is limited to 24 hours max."),

    h2("13.11 'How would you improve the system?'"),
    bul("Empirical weight calibration: right now the recommendation weights (40, 30, 20, 10) are educated guesses. If we tracked outcomes (which students got recommendations, which careers they actually pursued, which were successful), we could calibrate the weights against real data."),
    bul("Automated prerequisite discovery: instead of manually maintaining the 30+ prerequisite pairs, we could mine course descriptions and documentation for prerequisite statements and propose new pairs for human review."),
    bul("Mock interview module: using Gemini's conversational capability for realistic technical interviews tailored to the student's target career."),
    bul("Resume builder: not just analyzing resumes, but helping students build them with real-time ATS feedback."),
    bul("Live job posting integration: connect to LinkedIn/Indeed APIs to show real current openings and perform direct resume-to-JD matching."),
    bul("Mobile app: React Native frontend sharing the same REST backend."),

    h2("13.12 'Tell me about a bug you encountered and how you fixed it'"),
    p("The most memorable bug: users would complete email verification successfully, but during testing with React StrictMode, they would sometimes see an error message saying 'token already used' even though the verification worked."),
    p("The root cause: React's StrictMode intentionally double-fires effects in development to help catch side effects. So the verification API call would run twice with the same token. The first call would succeed and mark the token as used. The second call would find the token marked as used and return an error."),
    p("The fix had two parts. On the frontend: use a useRef to track whether the effect has run and skip the second call. On the backend: if a token has already been used but the associated user is already verified, return success instead of an error. This way the user sees success regardless."),
    p("This taught me to think about double-calls and idempotency. Production systems face network retries and other conditions that cause requests to be replayed. Endpoints should be designed to handle being called multiple times with the same parameters."),

    sp(),sp(),
    cen("— End of Technical Breakdown —",{italics:true,size:22}),
  ] }]
});

Packer.toBuffer(doc).then(buf => {
fs.writeFileSync('AI Career Guidance Agent_Technical_Breakdown.docx', buf);
  console.log('Technical breakdown document created successfully!');
}).catch(e => { console.error('Error:', e); process.exit(1); });